Repository YJU-OKURA/project_minori-nest-deployment-repo, pull requests merged in 2024-02, with the labels that each got.

#20 Create ci.yml
  .github/workflows/ci.yml
Labels: 🌏 Deploy, ⏰ P2

#21 環境設定
  .dockerignore
  .github/workflows/ci.yml
  .gitignore
  .prettierrc
  DockerFile
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.module.ts
  src/common/utils/swagger.util.ts
  src/common/utils/winston.util.ts
  src/main.ts
  src/middlewares/logger.middleware.ts
  src/utils/swagger.util.ts
  src/utils/winston.util.ts
  test/app.e2e-spec.ts
Labels: ⚙ Setting, 🆗 safe

#22 CIファイル、DockerFile修正
  .github/workflows/ci.yml
  .gitignore
  DockerFile
Labels: 🌏 Deploy, ⏰ P2, 🆗 safe

#23 PrismaORMの設定
  package-lock.json
  package.json
  prisma/migrations/20240215143616_init/migration.sql
  prisma/migrations/20240216043833_capitalization to model names/migration.sql
  prisma/migrations/20240216050231_alter column of materials/migration.sql
  prisma/migrations/20240216082125_add cascade constraint/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/common/configs/config.interface.ts
  src/common/configs/config.ts
  src/main.ts
Labels: ✨ Feature, ⚙ Setting, 🆗 safe

#25 PRテンプレートから不要な部分を削除
  .github/pull_request_template.md
Labels: 📃 Docs, ⏰ P3

#26 GitHub Actionsの自動レビュワーと自動アサインのロジック改善
  .github/auto_assign.yml
  .github/auto_be_reviewer.yml
  .github/workflows/auto-issue-assign.yml
  .github/workflows/auto-member.yml
  .github/workflows/auto-reviewer.yml
Labels: 🔨 Refactor, ⚙ Setting, 🐞 BugFix, ⏰ P3

#27 CD構築の設定
  .dockerignore
  .github/workflows/cd.yml
  DockerFile
Labels: 🌏 Deploy, ⏰ P2, 🆗 safe

#28 cd.yml ファイルのタイプミスを修正
  .github/workflows/cd.yml
Labels: 🌏 Deploy, 🐞 BugFix, 🆗 safe

#30 dependency追加
  package-lock.json
  package.json
Labels: 🐞 BugFix, 🆗 safe

#31 seeding関連ファイルおよびprismaのインスタンスのテストファイル追加
  package.json
  prisma/seed.ts
  src/app.module.ts
  src/common/configs/config.interface.ts
  src/common/configs/config.ts
  src/prisma/prisma.module.ts
  src/prisma/prisma.service.spec.ts
  src/prisma/prisma.service.ts
Labels: ✨ Feature, ✅ Test

#34 Dockerfile修正およびCDworkflowの修正
  .github/workflows/cd.yml
  DockerFile
Labels: 🌏 Deploy, 🆗 safe

#35 CDファイルの修正
  .github/workflows/cd.yml
Labels: 🌏 Deploy, 🆗 safe

#37 Trelloリンク連動機能の追加によるGitHub課題テンプレートの改善
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: 📃 Docs, ⚙ Setting, ⏰ P3

#39 Trelloリンク連動機能の追加によるGitHub PRテンプレートの改善
  .github/pull_request_template.md
Labels: 📃 Docs, ⚙ Setting, ⏰ P3

#40 認証の実装
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/auth.service.spec.ts
  src/auth/auth.service.ts
  src/common/decorators/role.decorator.ts
  src/common/guards/auth.guard.ts
  src/common/guards/role.guard.ts
Labels: ✨ Feature, ✅ Test, 🆗 safe

#41 schema.prismaファイルの修正
  package.json
  prisma/migrations/20240221134850_update_table_names_for_singular_model_names/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/common/guards/role.guard.ts
  src/main.ts
  src/modules/app/app.controller.spec.ts
  src/modules/app/app.controller.ts
  src/modules/app/app.module.ts
  src/modules/app/app.service.ts
  src/modules/auth/auth.module.ts
  src/modules/auth/auth.service.spec.ts
  src/modules/auth/auth.service.ts
  src/modules/prisma/prisma.module.ts
  src/modules/prisma/prisma.service.spec.ts
  src/modules/prisma/prisma.service.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.json
Labels: ✅ Test, 🔨 Refactor, ⚙ Setting, ⏰ P3, 🆗 safe

#43 資料のアップロードおよび管理機能の実装
  .github/workflows/cd.yml
  package-lock.json
  package.json
  src/common/configs/config.interface.ts
  src/common/configs/config.ts
  src/common/decorators/api-auth.decorator.ts
  src/common/decorators/api-file.decorator.ts
  src/common/decorators/api-response.decorator.ts
  src/common/decorators/role.decorator.ts
  src/common/decorators/use-role-guards.decorator.ts
  src/common/guards/auth.guard.ts
  src/common/guards/role.guard.ts
  src/common/interceptors/bigint.interceptor.ts
  src/common/interceptors/response.interceptor.ts
  src/common/pipes/file.pipe.ts
  src/common/utils/response.util.ts
  src/common/utils/swagger.util.ts
  src/main.ts
  src/modules/app/app.module.ts
  src/modules/langchain/langchain.module.ts
  src/modules/langchain/langchain.service.ts
  src/modules/material/dto/create.dto.ts
  src/modules/material/dto/update.dto.ts
  src/modules/material/entity/material.entity.ts
  src/modules/material/material.controller.spec.ts
  src/modules/material/material.controller.ts
  src/modules/material/material.module.ts
  src/modules/material/material.repository.ts
  src/modules/material/material.service.ts
  src/modules/upload/upload.module.ts
  src/modules/upload/upload.service.ts
Labels: ✨ Feature, ✅ Test, 🌏 Deploy, 🐞 BugFix, 📬 API, ⏰ P1, 🆗 safe
