Repository YJU-OKURA/project_minori-nest-deployment-repo, pull requests merged in 2024-01, with the labels that each got.

#4 OpenAIを活用したコードレビューボットの導入
  .github/workflows/cr.yml
Labels: ⚙ Setting

#6 自動割り当て機能のためのGitHub Actions設定の追加
  .github/workflows/auto-assign.yml
Labels: ⚙ Setting, ⏰ P3

#7 開発環境設定
  .eslintrc.js
  .gitignore
  .prettierrc
  nest-cli.json
  package-lock.json
  package.json
  src/app.controller.spec.ts
  src/app.controller.ts
  src/app.module.ts
  src/app.service.ts
  src/main.ts
  src/middlewares/logger.middleware.ts
  src/utils/swagger.util.ts
  src/utils/winston.util.ts
  test/app.e2e-spec.ts
  test/jest-e2e.json
  tsconfig.build.json
  tsconfig.json
Labels: ⚙ Setting

#11 GitHub Actionsの設定を修正して'Resource not accessible by integration'エラーを解消
  .github/workflows/auto-assign.yml
Labels: 🐞 BugFix, ⏰ P3

#13 自動Reviewer当て機能のためのGitHub Actions設定の追加
  .github/workflows/auto-reviewer.yml
  .github/workflows/auto_be_reviewer.yml
Labels: ⚙ Setting, ⏰ P3

#16 Github Actionsの設定変更：'pull_request'イベントを'pull_request_target'イベントに置き換え
  .github/auto_be_reviewer.yml
  .github/workflows/auto-assign.yml
Labels: ⚙ Setting, 🐞 BugFix, ⏰ P3
